### ISSUE TITLE
[BUG] object allocation during garbage collection phase

### ISSUE THREAD

**Issue by ccastillop** [pluginaweek/state_machine#123]
I am stuck in strange error. 
Ror 3.09 ruby 1.9.2 p290

Trying to POST or PUT some changes to newly created TransactionRequest object... 

My ActiveRecord class:

``` ruby
class TransactionRequest < ActiveRecord::Base

  belongs_to :user

  #better security to the transaction_requests  
  attr_accessible :amount_to_send, :currency_to_send, :platform_id,
                         :recipient_id, :currency_to_receive,
                         :payment_method_id, :agency_id, 
                         :receiver_agent_id, :receiver_account
...../ ...

  #- state machine
  state_machine :state, :initial => :new do
    state :new, :pending, :confirmed, :canceled, :paid, :delivered, :rejected
    event :to_pending do
      transition [:new, :pending] => :pending
    end
    event :confirm do
      transition :pending => :confirmed
    end
    event :cancel do
      transition :pending => :canceled
    end
    event :pay do
      transition :confirmed => :paid
    end
    event :reject do
      transition :paid => :rejected
    end
    event :deliver do
      transition :paid => :delivered  
    end
  end

  #estados de cumplimiento
  state_machine :compliance, :initial => :released do
    state :released, :retained
    event :retained do
      transition :released => :retained
    end
    event :release do
      transition :retained => :released
    end
  end

end

# == Schema Information
#
# Table name: transaction_requests
#
#  id                   :integer(4)      not null, primary key
# ... / ...
#  state                :string(255)
#  compliance           :string(255)
#  created_at           :datetime
#  updated_at           :datetime
#

```

Error stack:

/home/cristian/.rvm/gems/ruby-1.9.2-p290@senddinero/gems/activesupport-3.0.9/lib/active_support/whiny_nil.rb:48: [BUG] object allocation during garbage collection phase
ruby 1.9.2p290 (2011-07-09 revision 32553) [i686-linux]

-- control frame ----------
c:3636 p:0054 s:13984 b:13984 l:003983 d:003983 METHOD /home/cristian/.rvm/gems/ruby-1.9.2-p290@senddinero/gems/activesupport-3.0.9/lib/active_support/whiny_nil.rb:48
c:3635 p:---- s:13977 b:13977 l:003976 d:003976 FINISH
c:3634 p:---- s:13975 b:13975 l:003974 d:003974 CFUNC  :join
c:3633 p:0065 s:13972 b:13971 l:003946 d:003970 BLOCK  /home/cristian/.rvm/gems/ruby-1.9.2-p290@senddinero/gems/state_machine-1.0.2/lib/state_machine/integrations/active_model.rb:524
c:3632 p:---- s:13968 b:13968 l:003967 d:003967 FINISH
c:3631 p:---- s:13966 b:13966 l:003965 d:003965 CFUNC  :each
c:3630 p:0019 s:13963 b:13963 l:003946 d:003962 BLOCK  /home/cristian/.rvm/gems/ruby-1.9.2-p290@senddinero/gems/state_machine-1.0.2/lib/state_machine/integrations/active_model.rb:522
c:3629 p:---- s:13960 b:13960 l:003959 d:003959 FINISH
c:3628 p:---- s:13958 b:13958 l:003957 d:003957 CFUNC  :each
c:3627 p:0019 s:13955 b:13955 l:003946 d:003954 BLOCK  /home/cristian/.rvm/gems/ruby-1.9.2-p290@senddinero/gems/state_machine-1.0.2/lib/state_machine/integrations/active_model.rb:521
c:3626 p:---- s:13952 b:13952 l:003951 d:003951 FINISH
c:3625 p:---- s:13950 b:13950 l:003949 d:003949 CFUNC  :each
c:3624 p:0079 s:13947 b:13947 l:003946 d:003946 METHOD /home/cristian/.rvm/gems/ruby-1.9.2-p290@senddinero/gems/state_machine-1.0.2/lib/state_machine/integrations/active_model.rb:520
c:3623 p:0017 s:13937 b:13937 l:fffff52c d:003936 BLOCK  /home/cristian/.rvm/gems/ruby-1.9.2-p290@senddinero/gems/state_machine-1.0.2/lib/state_machine/integrations/active_model.rb:436
c:3622 p:---- s:13933 b:13933 l:003932 d:003932 FINISH
c:3621 p:---- s:13931 b:13931 l:003930 d:003930 CFUNC  :call
----- continues...

c:0003 p:0126 s:0009 b:0009 l:ffffe98c d:000008 BLOCK  /home/cristian/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/webrick/server.rb:183
c:0002 p:---- s:0004 b:0004 l:000003 d:000003 FINISH
## c:0001 p:---- s:0002 b:0002 l:000001 d:000001 TOP   

-- Ruby level backtrace information ----------------------------------------
/home/cristian/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/webrick/server.rb:183:in `block in start_thread'
/home/cristian/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/webrick/httpserver.rb:70:in`run'
/home/cristian/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/webrick/httpserver.rb:111:in `service'
/home/cristian/.rvm/gems/ruby-1.9.2-p290@senddinero/gems/rack-1.2.3/lib/rack/handler/webrick.rb:52:in`service'
/home/cristian/.rvm/gems/ruby-1.9.2-p290@senddinero/gems/rack-1.2.3/lib/rack/content_length.rb:13:in `call'
/home/cristian/.rvm/gems/ruby-1.9.2-p290@senddinero/gems/railties-3.0.9/lib/rails/rack/log_tailer.rb:14:in`call'
/home/cristian/.rvm/gems/ruby-1.9.2-p290@senddinero/gems/railties-3.0.9/lib/rails/application.rb:77:in `method_missing'
/home/cristian/.rvm/gems/ruby-1.9.2-p290@senddinero/gems/railties-3.0.9/lib/rails/application.rb:168:in`call'
/home/cristian/.rvm/gems/ruby-1.9.2-p290@senddinero/gems/actionpack-3.0.9/lib/action_dispatch/middleware/static.rb:30:in `call'
/home/cristian/.rvm/gems/ruby-1.9.2-p290@senddinero/gems/rack-1.2.3/lib/rack/lock.rb:11:in`call'
internal:prelude:10:in `synchronize'
/home/cristian/.rvm/gems/ruby-1.9.2-p290@senddinero/gems/rack-1.2.3/lib/rack/lock.rb:11:in`block in call'
/home/cristian/.rvm/gems/ruby-1.9.2-p290@senddinero/gems/activesupport-3.0.9/lib/active_support/cache/strategy/local_cache.rb:72:in `call'
/home/cristian/.rvm/gems/ruby-1.9.2-p290@senddinero/gems/rack-1.2.3/lib/rack/runtime.rb:17:in`call'
/home/cristian/.rvm/gems/ruby-1.9.2-p290@senddinero/gems/railties-3.0.9/lib/rails/rack/logger.rb:13:in `call'
/home/cristian/.rvm/gems/ruby-1.9.2-p290@senddinero/gems/actionpack-3.0.9/lib/action_dispatch/middleware/show_exceptions.rb:47:in`call'
/home/cristian/.rvm/gems/ruby-1.9.2-p290@senddinero/gems/actionpack-3.0.9/lib/action_dispatch/middleware/remote_ip.rb:48:in `call'
/home/cristian/.rvm/gems/ruby-1.9.2-p290@senddinero/gems/rack-1.2.3/lib/rack/sendfile.rb:107:in`call'
/home/cristian/.rvm/gems/ruby-1.9.2-p290@senddinero/gems/actionpack-3.0.9/lib/action_dispatch/middleware/callbacks.rb:44:in `call'
/home/cristian/.rvm/gems/ruby-1.9.2-p290@senddinero/gems/activesupport-3.0.9/lib/active_support/callbacks.rb:416:in`_run_call_callbacks'
/home/cristian/.rvm/gems/ruby-1.9.2-p290@senddinero/gems/actionpack-3.0.9/lib/action_dispatch/middleware/callbacks.rb:46:in `block in call'
/home/cristian/.rvm/gems/ruby-1.9.2-p290@senddinero/gems/activerecord-3.0.9/lib/active_record/connection_adapters/abstract/connection_pool.rb:354:in`call'
/home/cristian/.rvm/gems/ruby-1.9.2-p290@senddinero/gems/activerecord-3.0.9/lib/active_record/query_cache.rb:31:in `call'
/home/cristian/.rvm/gems/ruby-1.9.2-p290@senddinero/gems/activerecord-3.0.9/lib/active_record/query_cache.rb:12:in`cache'
/home/cristian/.rvm/gems/ruby-1.9.2-p290@senddinero/gems/activerecord-3.0.9/lib/active_record/connection_adapters/abstract/query_cache.rb:28:in `cache'
/home/cristian/.rvm/gems/ruby-1.9.2-p290@senddinero/gems/activerecord-3.0.9/lib/active_record/query_cache.rb:32:in`block in call'
/home/cristian/.rvm/gems/ruby-1.9.2-p290@senddinero/gems/actionpack-3.0.9/lib/action_dispatch/middleware/cookies.rb:302:in `call'
/home/cristian/.rvm/gems/ruby-1.9.2-p290@senddinero/gems/actionpack-3.0.9/lib/action_dispatch/middleware/session/abstract_store.rb:149:in`call'
/home/cristian/.rvm/gems/ruby-1.9.2-p290@senddinero/gems/actionpack-3.0.9/lib/action_dispatch/middleware/flash.rb:182:in `call'
/home/cristian/.rvm/gems/ruby-1.9.2-p290@senddinero/gems/actionpack-3.0.9/lib/action_dispatch/middleware/params_parser.rb:21:in`call'
/home/cristian/.rvm/gems/ruby-1.9.2-p290@senddinero/gems/rack-1.2.3/lib/rack/methodoverride.rb:24:in `call'
/home/cristian/.rvm/gems/ruby-1.9.2-p290@senddinero/gems/actionpack-3.0.9/lib/action_dispatch/middleware/head.rb:14:in`call'
/home/cristian/.rvm/gems/ruby-1.9.2-p290@senddinero/gems/actionpack-3.0.9/lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
/home/cristian/.rvm/gems/ruby-1.9.2-p290@senddinero/gems/warden-1.0.5/lib/warden/manager.rb:34:in`call'
/home/cristian/.rvm/gems/ruby-1.9.2-p290@senddinero/gems/warden-1.0.5/lib/warden/manager.rb:34:in `catch'
/home/cristian/.rvm/gems/ruby-1.9.2-p290@senddinero/gems/warden-1.0.5/lib/warden/manager.rb:35:in`block in call'
/home/cristian/.rvm/gems/ruby-1.9.2-p290@senddinero/gems/sass-3.1.7/lib/sass/plugin/rack.rb:54:in `call'
/home/cristian/.rvm/gems/ruby-1.9.2-p290@senddinero/gems/actionpack-3.0.9/lib/action_dispatch/routing/route_set.rb:493:in`call'
/home/cristian/.rvm/gems/ruby-1.9.2-p290@senddinero/gems/rack-mount-0.6.14/lib/rack/mount/route_set.rb:139:in `call'
/home/cristian/.rvm/gems/ruby-1.9.2-p290@senddinero/gems/rack-mount-0.6.14/lib/rack/mount/code_generation.rb:92:in`recognize'
/home/cristian/.rvm/gems/ruby-1.9.2-p290@senddinero/gems/rack-mount-0.6.14/lib/rack/mount/code_generation.rb:68:in `optimized_each'
/home/cristian/.rvm/gems/ruby-1.9.2-p290@senddinero/gems/rack-mount-0.6.14/lib/rack/mount/code_generation.rb:93:in`block in recognize'
/home/cristian/.rvm/gems/ruby-1.9.2-p290@senddinero/gems/rack-mount-0.6.14/lib/rack/mount/route_set.rb:148:in `block in call'
/home/cristian/.rvm/gems/ruby-1.9.2-p290@senddinero/gems/actionpack-3.0.9/lib/action_dispatch/routing/route_set.rb:27:in`call'
/home/cristian/.rvm/gems/ruby-1.9.2-p290@senddinero/gems/actionpack-3.0.9/lib/action_dispatch/routing/route_set.rb:62:in `dispatch'
/home/cristian/.rvm/gems/ruby-1.9.2-p290@senddinero/gems/actionpack-3.0.9/lib/action_dispatch/routing/route_set.rb:62:in`call'
/home/cristian/.rvm/gems/ruby-1.9.2-p290@senddinero/gems/actionpack-3.0.9/lib/action_controller/metal.rb:178:in `block in action'
/home/cristian/.rvm/gems/ruby-1.9.2-p290@senddinero/gems/actionpack-3.0.9/lib/action_controller/metal/rack_delegation.rb:14:in`dispatch'
/home/cristian/.rvm/gems/ruby-1.9.2-p290@senddinero/gems/actionpack-3.0.9/lib/action_controller/metal.rb:138:in `dispatch'
/home/cristian/.rvm/gems/ruby-1.9.2-p290@senddinero/gems/actionpack-3.0.9/lib/abstract_controller/rendering.rb:41:in`process'
/home/cristian/.rvm/gems/ruby-1.9.2-p290@senddinero/gems/actionpack-3.0.9/lib/abstract_controller/base.rb:119:in `process'
/home/cristian/.rvm/gems/ruby-1.9.2-p290@senddinero/gems/actionpack-3.0.9/lib/action_controller/metal/rescue.rb:17:in`process_action'
/home/cristian/.rvm/gems/ruby-1.9.2-p290@senddinero/gems/actionpack-3.0.9/lib/action_controller/metal/instrumentation.rb:29:in `process_action'
/home/cristian/.rvm/gems/ruby-1.9.2-p290@senddinero/gems/activesupport-3.0.9/lib/active_support/notifications.rb:52:in`instrument'
/home/cristian/.rvm/gems/ruby-1.9.2-p290@senddinero/gems/activesupport-3.0.9/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/home/cristian/.rvm/gems/ruby-1.9.2-p290@senddinero/gems/activesupport-3.0.9/lib/active_support/notifications.rb:52:in`block in instrument'
/home/cristian/.rvm/gems/ruby-1.9.2-p290@senddinero/gems/actionpack-3.0.9/lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
/home/cristian/.rvm/gems/ruby-1.9.2-p290@senddinero/gems/actionpack-3.0.9/lib/abstract_controller/callbacks.rb:17:in`process_action'
/home/cristian/.rvm/gems/ruby-1.9.2-p290@senddinero/gems/activesupport-3.0.9/lib/active_support/callbacks.rb:94:in `run_callbacks'
/home/cristian/.rvm/gems/ruby-1.9.2-p290@senddinero/gems/activesupport-3.0.9/lib/active_support/callbacks.rb:410:in`_run_process_action_callbacks'
/home/cristian/.rvm/gems/ruby-1.9.2-p290@senddinero/gems/activesupport-3.0.9/lib/active_support/callbacks.rb:446:in `_run__888355866__process_action__979906318__callbacks'
/home/cristian/.rvm/gems/ruby-1.9.2-p290@senddinero/gems/actionpack-3.0.9/lib/abstract_controller/callbacks.rb:18:in`block in process_action'
/home/cristian/.rvm/gems/ruby-1.9.2-p290@senddinero/gems/actionpack-3.0.9/lib/action_controller/metal/rendering.rb:11:in `process_action'
/home/cristian/.rvm/gems/ruby-1.9.2-p290@senddinero/gems/actionpack-3.0.9/lib/abstract_controller/base.rb:150:in`process_action'
/home/cristian/.rvm/gems/ruby-1.9.2-p290@senddinero/gems/actionpack-3.0.9/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
/home/cristian/Documentos/Webs/senddinero/app/controllers/transaction_requests_controller.rb:22:in`create'
/home/cristian/.rvm/gems/ruby-1.9.2-p290@senddinero/gems/activerecord-3.0.9/lib/active_record/transactions.rb:239:in `save'
/home/cristian/.rvm/gems/ruby-1.9.2-p290@senddinero/gems/activerecord-3.0.9/lib/active_record/transactions.rb:251:in`rollback_active_record_state!'
/home/cristian/.rvm/gems/ruby-1.9.2-p290@senddinero/gems/activerecord-3.0.9/lib/active_record/transactions.rb:240:in `block in save'
/home/cristian/.rvm/gems/ruby-1.9.2-p290@senddinero/gems/activerecord-3.0.9/lib/active_record/transactions.rb:290:in`with_transaction_returning_status'
/home/cristian/.rvm/gems/ruby-1.9.2-p290@senddinero/gems/activerecord-3.0.9/lib/active_record/transactions.rb:207:in `transaction'
/home/cristian/.rvm/gems/ruby-1.9.2-p290@senddinero/gems/activerecord-3.0.9/lib/active_record/connection_adapters/abstract/database_statements.rb:139:in`transaction'
/home/cristian/.rvm/gems/ruby-1.9.2-p290@senddinero/gems/activerecord-3.0.9/lib/active_record/transactions.rb:292:in `block in with_transaction_returning_status'
/home/cristian/.rvm/gems/ruby-1.9.2-p290@senddinero/gems/activerecord-3.0.9/lib/active_record/transactions.rb:240:in`block (2 levels) in save'
/home/cristian/.rvm/gems/ruby-1.9.2-p290@senddinero/gems/activerecord-3.0.9/lib/active_record/attribute_methods/dirty.rb:21:in `save'
/home/cristian/.rvm/gems/ruby-1.9.2-p290@senddinero/gems/activerecord-3.0.9/lib/active_record/validations.rb:43:in`save'
/home/cristian/.rvm/gems/ruby-1.9.2-p290@senddinero/gems/activerecord-3.0.9/lib/active_record/persistence.rb:40:in `save'
/home/cristian/.rvm/gems/ruby-1.9.2-p290@senddinero/gems/activerecord-3.0.9/lib/active_record/callbacks.rb:273:in`create_or_update'
/home/cristian/.rvm/gems/ruby-1.9.2-p290@senddinero/gems/activesupport-3.0.9/lib/active_support/callbacks.rb:414:in `_run_save_callbacks'
/home/cristian/.rvm/gems/ruby-1.9.2-p290@senddinero/gems/activesupport-3.0.9/lib/active_support/callbacks.rb:220:in`_conditional_callback_around_1977'
/home/cristian/.rvm/gems/ruby-1.9.2-p290@senddinero/gems/activesupport-3.0.9/lib/active_support/callbacks.rb:315:in `_callback_around_1975'
/home/cristian/.rvm/gems/ruby-1.9.2-p290@senddinero/gems/state_machine-1.0.2/lib/state_machine/integrations/active_record.rb:422:in`around_save'
/home/cristian/.rvm/gems/ruby-1.9.2-p290@senddinero/gems/state_machine-1.0.2/lib/state_machine/transition_collection.rb:62:in `perform'
/home/cristian/.rvm/gems/ruby-1.9.2-p290@senddinero/gems/state_machine-1.0.2/lib/state_machine/transition_collection.rb:185:in`within_transaction'
/home/cristian/.rvm/gems/ruby-1.9.2-p290@senddinero/gems/state_machine-1.0.2/lib/state_machine/transition_collection.rb:63:in `block in perform'
/home/cristian/.rvm/gems/ruby-1.9.2-p290@senddinero/gems/state_machine-1.0.2/lib/state_machine/transition_collection.rb:63:in`catch'
/home/cristian/.rvm/gems/ruby-1.9.2-p290@senddinero/gems/state_machine-1.0.2/lib/state_machine/transition_collection.rb:63:in `block (2 levels) in perform'
/home/cristian/.rvm/gems/ruby-1.9.2-p290@senddinero/gems/state_machine-1.0.2/lib/state_machine/transition_collection.rb:211:in`run_callbacks'
/home/cristian/.rvm/gems/ruby-1.9.2-p290@senddinero/gems/state_machine-1.0.2/lib/state_machine/transition_collection.rb:132:in `run_callbacks'
/home/cristian/.rvm/gems/ruby-1.9.2-p290@senddinero/gems/state_machine-1.0.2/lib/state_machine/transition_collection.rb:147:in`run_actions'
/home/cristian/.rvm/gems/ruby-1.9.2-p290@senddinero/gems/state_machine-1.0.2/lib/state_machine/transition_collection.rb:169:in `catch_exceptions'
/home/cristian/.rvm/gems/ruby-1.9.2-p290@senddinero/gems/state_machine-1.0.2/lib/state_machine/transition_collection.rb:149:in`block in run_actions'
/home/cristian/.rvm/gems/ruby-1.9.2-p290@senddinero/gems/state_machine-1.0.2/lib/state_machine/integrations/active_record.rb:422:in `block in around_save'
/home/cristian/.rvm/gems/ruby-1.9.2-p290@senddinero/gems/activesupport-3.0.9/lib/active_support/callbacks.rb:221:in`block in _conditional_callback_around_1977'
/home/cristian/.rvm/gems/ruby-1.9.2-p290@senddinero/gems/activesupport-3.0.9/lib/active_support/callbacks.rb:470:in `block in _run_save_callbacks'
/home/cristian/.rvm/gems/ruby-1.9.2-p290@senddinero/gems/activerecord-3.0.9/lib/active_record/callbacks.rb:273:in`block in create_or_update'
/home/cristian/.rvm/gems/ruby-1.9.2-p290@senddinero/gems/activerecord-3.0.9/lib/active_record/persistence.rb:250:in `create_or_update'
/home/cristian/.rvm/gems/ruby-1.9.2-p290@senddinero/gems/activerecord-3.0.9/lib/active_record/callbacks.rb:277:in`create'
/home/cristian/.rvm/gems/ruby-1.9.2-p290@senddinero/gems/activesupport-3.0.9/lib/active_support/callbacks.rb:415:in `_run_create_callbacks'
/home/cristian/Documentos/Webs/senddinero/app/models/transaction_request.rb:101:in`go_pending'
/home/cristian/.rvm/gems/ruby-1.9.2-p290@senddinero/gems/state_machine-1.0.2/lib/state_machine/machine.rb:704:in `block (2 levels) in define_helper'
/home/cristian/.rvm/gems/ruby-1.9.2-p290@senddinero/gems/state_machine-1.0.2/lib/state_machine/machine.rb:704:in`call'
/home/cristian/.rvm/gems/ruby-1.9.2-p290@senddinero/gems/state_machine-1.0.2/lib/state_machine/event.rb:223:in `block in add_actions'
/home/cristian/.rvm/gems/ruby-1.9.2-p290@senddinero/gems/state_machine-1.0.2/lib/state_machine/machine.rb:704:in`block (2 levels) in define_helper'
/home/cristian/.rvm/gems/ruby-1.9.2-p290@senddinero/gems/state_machine-1.0.2/lib/state_machine/machine.rb:704:in `call'
/home/cristian/.rvm/gems/ruby-1.9.2-p290@senddinero/gems/state_machine-1.0.2/lib/state_machine/event.rb:218:in`block in add_actions'
/home/cristian/.rvm/gems/ruby-1.9.2-p290@senddinero/gems/state_machine-1.0.2/lib/state_machine/event.rb:158:in `fire'
/home/cristian/.rvm/gems/ruby-1.9.2-p290@senddinero/gems/state_machine-1.0.2/lib/state_machine/transition.rb:209:in`perform'
/home/cristian/.rvm/gems/ruby-1.9.2-p290@senddinero/gems/state_machine-1.0.2/lib/state_machine/transition_collection.rb:60:in `perform'
/home/cristian/.rvm/gems/ruby-1.9.2-p290@senddinero/gems/state_machine-1.0.2/lib/state_machine/transition_collection.rb:147:in`run_actions'
/home/cristian/.rvm/gems/ruby-1.9.2-p290@senddinero/gems/state_machine-1.0.2/lib/state_machine/transition_collection.rb:169:in `catch_exceptions'
/home/cristian/.rvm/gems/ruby-1.9.2-p290@senddinero/gems/state_machine-1.0.2/lib/state_machine/transition_collection.rb:153:in`block in run_actions'
/home/cristian/.rvm/gems/ruby-1.9.2-p290@senddinero/gems/state_machine-1.0.2/lib/state_machine/transition_collection.rb:153:in `each'
/home/cristian/.rvm/gems/ruby-1.9.2-p290@senddinero/gems/state_machine-1.0.2/lib/state_machine/transition_collection.rb:153:in`block (2 levels) in run_actions'

------ continues...

**Comment by ccastillop** [comment]
I found out the solution: I was setting some state value before_validation, so Ruby enter in an infinite bucle...
