### ISSUE TITLE
warning: undefining `initialize'

### ISSUE THREAD

**Issue by obrie** [pluginaweek/state_machine#15]
**tsechingho** opened this issue

yesterday i check out the new version state machine for my previous project using old version state machine and rails 2.2.2. I encounter two situation which can be produced many times.

(1) **/opt/local/lib/ruby/gems/1.8/gems/activerecord-2.2.2/lib/active_record/base.rb:410: warning: undefining `initialize&rsquo; may cause serious problem**

I get this waring whether in my previous project or a brand new rails project (rails 2.2.2). The code is as simple as:

 @@@ ruby
class User < ActiveRecord::Base
  state_machine :initial => &rsquo;passive&rsquo; do
    event :activate do
      transition :to => &rsquo;active&rsquo;, :from => &rsquo;pending&rsquo;
    end
  end
end
 @@@

(2) And I can not migrate from the blank database(schema not yet have) in my previous project change to new version state machine. **But brand new rails project can do this**. I know this maybe is my own problem, but anyone has any suggestion?

 @@@
rake db:migrate --trace
rake aborted!
Could not find table &rsquo;users&rsquo;

*\* Invoke db:migrate (first_time)
*\* Invoke environment (first_time)
*\* Execute environment
rake aborted!
Could not find table &rsquo;users&rsquo;
/opt/local/lib/ruby/gems/1.8/gems/activerecord-2.2.2/lib/active_record/connection_adapters/sqlite3_adapter.rb:29:in `table_structure&rsquo;
/opt/local/lib/ruby/gems/1.8/gems/activesupport-2.2.2/lib/active_support/core_ext/object/misc.rb:39:in`returning&rsquo;
/opt/local/lib/ruby/gems/1.8/gems/activerecord-2.2.2/lib/active_record/connection_adapters/sqlite3_adapter.rb:28:in `table_structure&rsquo;
/opt/local/lib/ruby/gems/1.8/gems/activerecord-2.2.2/lib/active_record/connection_adapters/sqlite_adapter.rb:189:in`columns&rsquo;
/opt/local/lib/ruby/gems/1.8/gems/activerecord-2.2.2/lib/active_record/base.rb:1220:in `columns&rsquo;
/opt/local/lib/ruby/gems/1.8/gems/activerecord-2.2.2/lib/active_record/base.rb:1228:in`columns_hash&rsquo;
/opt/local/lib/ruby/gems/1.8/gems/activerecord-2.2.2/lib/active_record/attribute_methods.rb:71:in `define_attribute_methods&rsquo;
/Users/tsechingho/Desktop/Facebook/trunk/vendor/plugins/state_machine/lib/state_machine/integrations/active_record.rb:194:in`define_attribute_accessor&rsquo;
/Users/tsechingho/Desktop/Facebook/trunk/vendor/plugins/state_machine/lib/state_machine/machine.rb:244:in `initialize&rsquo;
/Users/tsechingho/Desktop/Facebook/trunk/vendor/plugins/state_machine/lib/state_machine/machine.rb:184:in`new&rsquo;
/Users/tsechingho/Desktop/Facebook/trunk/vendor/plugins/state_machine/lib/state_machine/machine.rb:184:in `find_or_create&rsquo;
/Users/tsechingho/Desktop/Facebook/trunk/vendor/plugins/state_machine/lib/state_machine.rb:129:in`state_machine&rsquo;
/Users/tsechingho/Desktop/Facebook/trunk/lib/authorization/statable_roles.rb:69:in `included&rsquo;
/Users/tsechingho/Desktop/Facebook/trunk/lib/authorization/statable_roles.rb:66:in`class_eval&rsquo;
/Users/tsechingho/Desktop/Facebook/trunk/lib/authorization/statable_roles.rb:66:in `included&rsquo;
/Users/tsechingho/Desktop/Facebook/trunk/app/models/user.rb:8:in`include&rsquo;
/Users/tsechingho/Desktop/Facebook/trunk/app/models/user.rb:8
 @@@

[original LH ticket](http://pluginaweek.lighthouseapp.com/projects/13288/tickets/5)

 This ticket has 0 attachment(s).

**Comment by obrie** [comment]
(from [c3d532f50b2cf0f9f8eddb1ac2c81e71a07eb1ce]) Fix ActiveRecord state machines trying to query the database on unmigrated models [#5]
http://github.com/pluginaweek/state_machine/commit/c3d532f50b2cf0f9f8eddb1ac2c81e71a07eb1ce

**Comment by obrie** [comment]
(from [06e8e845b583fc229ee023dd63abc390e266472e]) Fix aliasing :initialize on ActiveRecord models causing warnings when the environment is reloaded [#5 state:resolved]
http://github.com/pluginaweek/state_machine/commit/06e8e845b583fc229ee023dd63abc390e266472e

**Comment by obrie** [comment]
Thanks for the detailed report!  Helped uncover some great ActiveRecord edge cases.

**Comment by obrie** [comment]
**tsechingho** commented

Thanks for fix, it does help a lot.
