### ISSUE TITLE
unpredictable results for "?" methods for multiple state_machines

### ISSUE THREAD

**Issue by obrie** [pluginaweek/state_machine#17]
**Aaron Gibralter** opened this issue

Does state_machine define methods to test the current state? The github README examples seem to show that vehicle.parked? will say whether or not the vehicle is parked. I&rsquo;ve been getting kind of unpredictable behavior with my models with multiple state_machines. For some of them the "?" methods work and others don&rsquo;t:

 @@@
# class User ...

state_machine :state_password, :initial => &rsquo;known&rsquo; do
  # ... events for &rsquo;forgotten&rsquo; and &rsquo;known&rsquo; passwords
end

state_machine :state_email, :initial => &rsquo;unverified&rsquo; do
  # ... events for &rsquo;unverified&rsquo; and &rsquo;verified&rsquo; email addresses
end

u.known? #=> NoMethodError: undefined method `known?&rsquo; for #User:0x3e51a48
 @@@

What about creating a method which takes the name of the state_machine as such:

 @@@
user.state_password?(&rsquo;known&rsquo;) #=> true
# or...

user.state_password_known? #=> true

user.state_email?(&rsquo;verified&rsquo;) #=> true
user.state_email?(&rsquo;unverified&rsquo;) #=> false
 @@@

[original LH ticket](http://pluginaweek.lighthouseapp.com/projects/13288/tickets/7)

 This ticket has 0 attachment(s).

**Comment by obrie** [comment]
Is this using ActiveRecord?

With regard to the predicate naming, you make a good point.  I was a bit reluctant adding in predicate methods because of conflicting names between multiple state machines, but I hadn&rsquo;t even thought about namespacing them :)

I&rsquo;ll have to give more thought into how predicate methods are generated and whether/when to namespace them.

**Comment by obrie** [comment]
Also, do you have a full example that replicates this behavior?  I&rsquo;m unable to in my environment.

**Comment by obrie** [comment]
**Aaron Gibralter** commented

Here are my state_machines for user.rb and some console output:

 @@@
class User < ActiveRecord::Base

  # ...

  state_machine :state_email, :initial => &rsquo;fresh&rsquo; do

```
before_transition :to => &rsquo;unverified&rsquo;, :do => :make_email_verification_code
before_transition :to => &rsquo;verified&rsquo;, :do => :set_email_verified_attributes

event :unverify do
  transition :to => &rsquo;unverified&rsquo;, :from => %w(unverified verified fresh)
end

event :verify do
  transition :to => &rsquo;verified&rsquo;, :from => %w(unverified verified fresh)
end
```

  end

  state_machine :state_password, :initial => &rsquo;known&rsquo; do

```
before_transition :to => &rsquo;forgotten&rsquo;, :do => :make_forgot_password_code
before_transition :to => &rsquo;known&rsquo;, :do => :clear_forgot_password_code

event :forgets_password do
  transition :to => &rsquo;forgotten&rsquo;, :from => %w(known forgotten)
end

event :remembers_password do
  transition :to => &rsquo;known&rsquo;, :from => &rsquo;forgotten&rsquo;
end
```

  end

  state_machine :state_news, :initial => &rsquo;pending&rsquo; do

```
before_transition :to => &rsquo;subscribed&rsquo;, :do => :make_demetri_code
before_transition :to => &rsquo;demetri&rsquo;, :do => :clear_demetri_code

event :become_demetri do
  transition :to => &rsquo;demetri&rsquo;, :from => %w(pending subscribed)
end

event :subscribe do
  transition :to => &rsquo;subscribed&rsquo;, :from => %w(pending demetri)
end

event :toggle_news do
  transition :to => &rsquo;subscribed&rsquo;, :from => &rsquo;demetri&rsquo;
  transition :to => &rsquo;demetri&rsquo;, :from => &rsquo;subscribed&rsquo;
end
```

  end

  state_machine :state_standing, :initial => &rsquo;neutral&rsquo; do

```
event :suspend do
  transition :to => &rsquo;suspended&rsquo;, :from => %w(neutral)
end

event :restore do
  transition :to => &rsquo;neutral&rsquo;, :from => %w(suspended)
end

event :toggle_standing do
  transition :to => &rsquo;suspended&rsquo;, :from => &rsquo;neutral&rsquo;
  transition :to => &rsquo;neutral&rsquo;, :from => &rsquo;suspended&rsquo;
end
```

  end

  # ...

end

# >> u = User.new

# >> u.verified?

# NoMethodError: undefined method `verified?&rsquo; for #User:0x3e51a5c

# from /Users/aarongibralter/Sites/urtak/vendor/rails/activerecord/lib/active_record/attribute_methods.rb:255:in `method_missing&rsquo;

# from (irb):2

# >> u.fresh?

# NoMethodError: undefined method `fresh?&rsquo; for #User:0x3e51a5c

# from /Users/aarongibralter/Sites/urtak/vendor/rails/activerecord/lib/active_record/attribute_methods.rb:255:in `method_missing&rsquo;

# from (irb):3

 @@@

Do you think it&rsquo;s something else in my environment or user.rb file? Should u.fresh? work?

**Comment by obrie** [comment]
Sorry for the dumb question, but just to verify the environments...  What versions of Ruby, Rails, and state_machine are you on?

**Comment by obrie** [comment]
**Aaron Gibralter** commented

Oh sorry, no that&rsquo;s my bad (not a dumb question at all) -- I forgot to include those:

state_machine: bee135e27fb88695a5f03f81130fa8b30671a86d
rails 2.2.2

I just saw there are newer commits -- I&rsquo;ll update and see if that changes anything.

**Comment by obrie** [comment]
From what I can tell, it looks like that implementation was added after that commit.

Also, FYI, I&rsquo;ll be adding a :namespace option on the state machine which will support doing something like so:

 @@@
state_machine :state_email, :initial => &rsquo;fresh&rsquo;, :namespace => &rsquo;email&rsquo; do
  event :unverify do
    transition :to => &rsquo;unverified&rsquo;, :from => %w(unverified verified fresh)
  end

  event :verify do
    transition :to => &rsquo;verified&rsquo;, :from => %w(unverified verified fresh)
  end
end
 @@@

...which will generate the following methods:
- unverify_email / unverify_email! / can_unverify_email? / etc.
- verify_email / verifiy_email! / can_verify_email? / etc.
- email_verified?
- email_unverified?
- email_fresh?
- etc.

**Comment by obrie** [comment]
**Aaron Gibralter** commented

Ah, great call!

**Comment by obrie** [comment]
