### ISSUE TITLE
Run event from rails callback before_create  

### ISSUE THREAD

**Issue by vad4msiu** [pluginaweek/state_machine#219]
I wrote a rails application [bug_state_machine](https://github.com/vad4msiu/bug_state_machine) showing error. I have a model Order:

```
class Order < ActiveRecord::Base
  attr_accessible :name, :state

  before_create :bug_callback, :if => :check_method

  state_machine :state, :initial => :new do
    event :complete do
      transition :new => :completed
    end
  end

  private

  def check_method
    true
  end

  def bug_callback
    complete
  end
end
```

When I try to create a model I get error:

```
1.9.3p125 :004 > Order.create!
   (0.1ms)  begin transaction
   (0.0ms)  rollback transaction
ActiveRecord::RecordNotSaved: ActiveRecord::RecordNotSaved
    from /Users/vad4msiu/.rvm/gems/ruby-1.9.3-p125/gems/activerecord-3.2.8/lib/active_record/persistence.rb:104:in `save!'
    from /Users/vad4msiu/.rvm/gems/ruby-1.9.3-p125/gems/activerecord-3.2.8/lib/active_record/validations.rb:56:in `save!'
    from /Users/vad4msiu/.rvm/gems/ruby-1.9.3-p125/gems/activerecord-3.2.8/lib/active_record/attribute_methods/dirty.rb:33:in `save!'
    from /Users/vad4msiu/.rvm/gems/ruby-1.9.3-p125/gems/activerecord-3.2.8/lib/active_record/transactions.rb:246:in `block in save!'
    from /Users/vad4msiu/.rvm/gems/ruby-1.9.3-p125/gems/activerecord-3.2.8/lib/active_record/transactions.rb:295:in `block in with_transaction_returning_status'
    from /Users/vad4msiu/.rvm/gems/ruby-1.9.3-p125/gems/activerecord-3.2.8/lib/active_record/connection_adapters/abstract/database_statements.rb:192:in `transaction'
    from /Users/vad4msiu/.rvm/gems/ruby-1.9.3-p125/gems/activerecord-3.2.8/lib/active_record/transactions.rb:208:in `transaction'
    from /Users/vad4msiu/.rvm/gems/ruby-1.9.3-p125/gems/activerecord-3.2.8/lib/active_record/transactions.rb:293:in `with_transaction_returning_status'
    from /Users/vad4msiu/.rvm/gems/ruby-1.9.3-p125/gems/activerecord-3.2.8/lib/active_record/transactions.rb:246:in `save!'
    from /Users/vad4msiu/.rvm/gems/ruby-1.9.3-p125/gems/activerecord-3.2.8/lib/active_record/validations.rb:41:in `create!'
    from (irb):4
    from /Users/vad4msiu/.rvm/gems/ruby-1.9.3-p125/gems/railties-3.2.8/lib/rails/commands/console.rb:47:in `start'
    from /Users/vad4msiu/.rvm/gems/ruby-1.9.3-p125/gems/railties-3.2.8/lib/rails/commands/console.rb:8:in `start'
    from /Users/vad4msiu/.rvm/gems/ruby-1.9.3-p125/gems/railties-3.2.8/lib/rails/commands.rb:41:in `<top (required)>'
    from script/rails:6:in `require'
    from script/rails:6:in `<main>'
1.9.3p125 :005 >
1.9.3p125 :001 > q = Order.new
 => #<Order id: nil, state: "new", name: nil, created_at: nil, updated_at: nil>
1.9.3p125 :002 > q.can_complete?
 => true
1.9.3p125 :003 > q.complete!
   (0.1ms)  begin transaction
   (0.0ms)  rollback transaction
StateMachine::InvalidTransition: Cannot transition state via :complete from :new (Reason(s): State cannot transition via "complete")
  from /Users/vad4msiu/.rvm/gems/ruby-1.9.3-p125/gems/state_machine-1.1.2/lib/state_machine/event.rb:241:in `block in add_actions'
  from /Users/vad4msiu/.rvm/gems/ruby-1.9.3-p125/gems/state_machine-1.1.2/lib/state_machine/machine.rb:753:in `call'
  from /Users/vad4msiu/.rvm/gems/ruby-1.9.3-p125/gems/state_machine-1.1.2/lib/state_machine/machine.rb:753:in `block (2 levels) in define_helper'
  from (irb):3
  from /Users/vad4msiu/.rvm/gems/ruby-1.9.3-p125/gems/railties-3.2.8/lib/rails/commands/console.rb:47:in `start'
  from /Users/vad4msiu/.rvm/gems/ruby-1.9.3-p125/gems/railties-3.2.8/lib/rails/commands/console.rb:8:in `start'
  from /Users/vad4msiu/.rvm/gems/ruby-1.9.3-p125/gems/railties-3.2.8/lib/rails/commands.rb:41:in `<top (required)>'
  from script/rails:6:in `require'
  from script/rails:6:in `<main>'
```

Why?

**Comment by obrie** [comment]
In general, I recommend against running transitions in `before_create` / `after_create` callbacks.  Note that when you invoke an event, that event also calls save.  Nesting multiple `save` calls within the initial creation of a record has a variety of side effects.  In order to make this work, you would have to explicitly skip the action like so:

``` ruby
# ...
  def bug_callback
    complete(false)
  end
# ...
```

Note that this will only be officially supported in the upcoming 1.2.0 release.

**Comment by vad4msiu** [comment]
Thank you!
