### ISSUE TITLE
pluralize issue

### ISSUE THREAD

**Issue by obrie** [pluginaweek/state_machine#23]
**Pete Forde** opened this issue

Hey Aaron,

I&rsquo;m sorry that what I&rsquo;m about to say isn&rsquo;t tested or particularly demonstrable, but in certain places in my app I seem to run into situations (under 2.2.2) where for some reason state_machine explodes and the whole mongrel instance needs to be restarted.

Here&rsquo;s an example:

<pre>
class User < ActiveRecord::Base
  state_machine :initial => :pending do
    event :activate do
      transition :from => :pending, :to => :active
    end
    event :reactivate do
      transition :from => :disabled, :to => :active
    end
    event :disable do
      transition :from => :active, :to => :disabled
    end
  end
end
</pre>

In this situation where the problem occurs, it bombs with a really long error stack:

<pre>
wrong number of arguments (0 for 2)

vendor/plugins/state_machine/lib/state_machine/machine.rb:1020:in `pluralize&rsquo;
vendor/plugins/state_machine/lib/state_machine/machine.rb:1020:in `define_scopes&rsquo;
vendor/plugins/state_machine/lib/state_machine/machine.rb:265:in `initialize&rsquo;
vendor/plugins/state_machine/lib/state_machine/machine.rb:171:in `new&rsquo;
vendor/plugins/state_machine/lib/state_machine/machine.rb:171:in `find_or_create&rsquo;
vendor/plugins/state_machine/lib/state_machine.rb:309:in `state_machine&rsquo;
app/models/user.rb:27
</pre>

Just to explain, line 27 of the User model is where I call state_machine.

After testing, I concluded that if on machine.rb line 1020 attribute is a Symbol, for some reason responds_to? returns true and it blows up.

Strangely, if I modify the call like so:

<pre>
attributes.pluralize(2, &rsquo;girl&rsquo;) # => plural is girls
</pre>

Anyhow, I tweaked my local plugin source so it looked more like this:

<pre>
plural = custom_plural || (attribute.respond_to?(:pluralize) ? attribute.to_s.pluralize : "#{attribute}s")
</pre>

And it works!

For some reason, sometimes attribute is a Symbol, which doesn&rsquo;t have a pluralize method. That said, I have no idea why attribute.respond_to? returns true in this case.

Hope this helps.

[original LH ticket](http://pluginaweek.lighthouseapp.com/projects/13288/tickets/13)

 This ticket has 0 attachment(s).

**Comment by obrie** [comment]
You&rsquo;re absolutely right :)  When I made the transition to no longer stringify attributes when being stored in the machine, the pluralization code wasn&rsquo;t adjusted properly... and there were no tests to catch it!

With regard to why the symbol sometimes responds to #pluralize, my guess is that at some point during your app&rsquo;s lifetime, there&rsquo;s a library somewhere that mixes in those additional methods into the Symbol class.

Thanks for the information... patch coming right up.

**Comment by obrie** [comment]
(from [cd16cad297f5bf1fcaae385b08d2e2a4aa19ad87]) Fix scope name pluralization not being applied correctly [#13 state:resolved]
http://github.com/pluginaweek/state_machine/commit/cd16cad297f5bf1fcaae385b08d2e2a4aa19ad87
