### ISSUE TITLE
around_validation error for Rails4.1.0beta

### ISSUE THREAD

**Issue by the-teacher** [pluginaweek/state_machine#251]
Hello! 

I have following problem:

```
Page.last.to_draft
  Page Load (0.2ms)  SELECT "pages".* FROM "pages" ORDER BY "pages"."id" DESC LIMIT 1
   (0.1ms)  begin transaction
   (0.1ms)  rollback transaction
NoMethodError: protected method `around_validation' called for #<StateMachine::Machine:0x00000004382b98>
```

```
bin/rails --version
Rails 4.1.0.beta
```

Maybe it's will be interesting for somebody.

Thank you!

**Comment by awsmsrc** [comment]
I have this too! Its being caused on a machinist .make! call.
Happy to help with more info!

**Comment by awsmsrc** [comment]
any update on this?

**Comment by awsmsrc** [comment]
this is a quick fix, I haven't looked into this more deeply to check for more serious repercussions. With a bit if guidance form a maintainer i'm happy to work on this

**Comment by pechorin** [comment]
bump, same problem on `rails (4.1.0.beta)`

**Comment by nesrual** [comment]
bump - same problem here using Rails 4.1.0.beta

```
NoMethodError:
  protected method `around_validation' called for #<StateMachine::Machine:0x007fb0c31c5608>
```

**Comment by wkrsz** [comment]
PR from @lukeroberts1990 fixes the problem for me (Rails HEAD)

**Comment by the-teacher** [comment]
Wow wow wow! It's steel doesn't work ((
I can't migrate to rails  4.1.0.beta1

**Comment by the-teacher** [comment]
config/initializers/state_machine_patch.rb

``` ruby
module StateMachine
  module Integrations
     module ActiveModel
        public :around_validation
     end
  end
end
```

**Comment by sid137** [comment]
@the-teacher   Thanks!   works great

**Comment by jurikern** [comment]
It's not worked for me, because same error for :around_save protected method (rails 4.1.0.beta1). 
Issue (config/initializers/state_machine_patch.rb):

``` ruby
module StateMachine
  module Integrations
     module ActiveModel
        public :around_validation
     end

     module ActiveRecord
        public :around_save
     end
  end
end
```

**Comment by sid137** [comment]
@kerny I am on rails edge, and that seems to work

**Comment by jurikern** [comment]
Seems like a after_transition not works for rails edge (ActiveRecord) to ...

**Comment by amacneil** [comment]
+1

**Comment by schaary** [comment]
+1

**Comment by miry** [comment]
+1

**Comment by jurikern** [comment]
Last time authored 10 months ago and 19 unresolved pull requests. Very sadly ...

**Comment by edbo** [comment]
@obrie Would be a shame to see state machine go stale, I'm a big fan. Rails is now at v4.1.0rc2 which I reckon means we're pretty close to the release which will make this officially 'broken' soon.

I'm sure some people in the community would be happy to help with maintenance.

**Comment by richpeck** [comment]
Same problem in 4.1.0 stable

**Comment by patrickespake** [comment]
+1
Same problem in 4.1.0 stable.

**Comment by cryo28** [comment]
+1

**Comment by MirkoMignini** [comment]
+1

**Comment by saboyutaka** [comment]
+1

**Comment by klaut** [comment]
+1

**Comment by nhoffmann** [comment]
+1

**Comment by simonmd** [comment]
+1

**Comment by simonmorley** [comment]
:+1:

**Comment by awsmsrc** [comment]
guys just use AASM (Acts As State Machine), its a shame to see this one go but its had no activity for a while

**Comment by hapiben** [comment]
+1

**Comment by jvanbaarsen** [comment]
@the-teacher Thanks for your comment, worked on rails 4.1!

**Comment by miclovich** [comment]
any chance, we can fork this in its own "state-machine" organization, @pluginaweek is probably extremely busy... this is an awesome gem though.

**Comment by dpickett** [comment]
I propose we create an official fork as this repository has become inactive. I've created a fork and organization here: https://github.com/pluginaweek-statemachine/state_machine

**Comment by jvanbaarsen** [comment]
@dpickett Was the organisation name "state-machine" or "statemachine" already in use? Since thats a bit shorter :D Thanks for the initiative though!

**Comment by dpickett** [comment]
Yeah unfortunately I had very limited options in that department. If anyone has a better idea I am happy to change it. I am also happy to add anyone as a collaborator that had a few changesets in this report, and I am willing to actively maintain this lib, as I use it pretty extensively. I personally loathe aasm so I would like to keep this alive.

**Comment by jvanbaarsen** [comment]
@dpickett ah ok :-)

**Comment by dpickett** [comment]
hey everyone! I was in touch with Aaron over the weekend to talk about Gem ownership and he was really quick to respond. He noted he needed a little personal time away from the library but he'll be jumping back into it. For more details, please refer to issue #310 - I've deleted my previously created organization and fork.

**Comment by miclovich** [comment]
:+1:

**Comment by cheshire137** [comment]
Still an issue on Rails 4.1.1.

**Comment by bobbus** [comment]
@dpickett , I would agree with @Dorian : there is no commit on this project since 1 year, this really looks like an abandoned project and it would probably prevent new user to choose this gem.

**Comment by JohnSmall** [comment]
This is a showstopper in Rails 4.1.1. 

Is anyone taking a look at it?

**Comment by tylercollier** [comment]
+1

**Comment by lucascaton** [comment]
+1

**Comment by thejchap** [comment]
+1

**Comment by DavidBennettPIO** [comment]
+1

**Comment by jeppeliisberg** [comment]
+1

**Comment by marcusg** [comment]
+1

**Comment by mattherick** [comment]
+1

**Comment by mhefferan** [comment]
+1

**Comment by annapetry** [comment]
I was getting the "NoMethodError....blah blah blah...protected method :around_validation..."

The error was happening in this file:  
/Users/[USERNAME]/.rvm/gems/ruby-2.1.1@global/gems/activerecord-4.1.0/lib/active_record/callbacks.rb

So I just went in there and made the following method public:

  def create_or_update #:nodoc:
      run_callbacks(:save) { super }
    end

Not sure that this is a good idea, but it worked.  I have the functionality I was looking for.

**Comment by malditojavi** [comment]
I'm testing the fix suggested by @annapetry, but I have no idea where to include my edit and what to include. My issue is not in the active record, but in the active support folder, I have uploaded the file in this gist if anyone can help - https://gist.github.com/malditojavi/dca63c7308808cf77f91

The issue is returning in the log is:

NoMethodError - protected method `around_validation' called for #<StateMachine::Machine:0x00000102676440>:
  activesupport (4.1.1) lib/active_support/callbacks.rb:447:in`block in make_lambda'
  activesupport (4.1.1) lib/active_support/callbacks.rb:298:in `block in halting'
  activesupport (4.1.1) lib/active_support/callbacks.rb:86:in`run_callbacks'
  activemodel (4.1.1) lib/active_model/validations/callbacks.rb:111:in `run_validations!'
  activemodel (4.1.1) lib/active_model/validations.rb:317:in`valid?'

**Comment by seuros** [comment]
@malditojavi 
Use my fork, if there is a problem there, i will fix it for you.

**Comment by malditojavi** [comment]
@seuros Worked great along the fix from @the-teacher, thanks both

**Comment by seuros** [comment]
I don't think you need the patch.

**Comment by malditojavi** [comment]
True, @seuros I didn't tested it without it, but it works

**Comment by melekes** [comment]
+1

**Comment by zdavis** [comment]
+1

**Comment by harakhovich** [comment]
@seuros a huge thanks to you, hope author will fix it

**Comment by mooreniemi** [comment]
+1

**Comment by thb** [comment]
+1

**Comment by creasty** [comment]
+1

**Comment by naserca** [comment]
+1

**Comment by derrek** [comment]
+1

**Comment by TomCawthorn** [comment]
+1

**Comment by the-teacher** [comment]
Hello!

Today I  decide - my gem TheComments will provide patch for StateMachine. I hope it will be helpful

https://github.com/the-teacher/the_comments/blob/master/lib/the_comments.rb#L24

``` ruby
if StateMachine::VERSION.to_f <= 1.2
puts '~' * 50
puts 'TheComments'
puts '~' * 50
puts 'WARNING!'
puts 'StateMachine patch for Rails4 will be applied'
puts
puts '> private method *around_validation* from StateMachine::Integrations::ActiveModel will be public'
puts
puts 'https://github.com/pluginaweek/state_machine/issues/295'
puts 'https://github.com/pluginaweek/state_machine/issues/251'
puts '~' * 50

module StateMachine::Integrations::ActiveModel
   public :around_validation
end

end
```

Simple patch still actual for rails 4.1.X

You can use it for any project which use StateMachine

``` ruby
module StateMachine::Integrations::ActiveModel
   public :around_validation
end
```

**Comment by the-teacher** [comment]
https://github.com/the-teacher/the_comments/issues/27

**Comment by arojoal** [comment]
+1

**Comment by jasdeepsingh** [comment]
Issue exists for Rails 4.2.0.beta1 too.

**Comment by lvl0nax** [comment]
+1

**Comment by maokomioko** [comment]
Maybe instead of continuously stamping +1, we can create a community fork and finally keep on with the development?

**Comment by awsmsrc** [comment]
we've been asked not to by a friend of @pluginaweek, i recommend using aasm in the meantime

**Comment by yordis** [comment]
+1

Rails 4.1.4
Ruby 2.1.1

**Comment by arnaudbouffard** [comment]
@the-teacher's comment with state_machine_patch.rb worked for me, thanks!
rails, '4.1.5'
ruby '2.1.1'

**Comment by lucascaton** [comment]
+1

**Comment by lucascaton** [comment]
@pluginaweek: any news on this one? Any change to bump the version with the fix?
Thanks.

**Comment by djedynak** [comment]
Hi, can someone please explain how to install @the-teacher's patch?

**Comment by gingermusketeer** [comment]
@djedynak I added a file `config/initializers/state_machine_patch.rb` to my rails app with the contents 

``` ruby
#See https://github.com/pluginaweek/state_machine/issues/251
module StateMachine
  module Integrations
     module ActiveModel
        public :around_validation
     end
  end
end
```

If you put @the-teacher's patch into that file instead it should do the trick as well

**Comment by Andrekra** [comment]
+1

**Comment by mhuggins** [comment]
+1 (cause my +1 is obviously going to make this happen compared to everyone else's :smile:)

**Comment by nhoffmann** [comment]
Thank you @mhuggins for making it happen :stuck_out_tongue:

**Comment by chriswoodrich** [comment]
+1 for @djedynak 's fix

**Comment by warpc** [comment]
+1 for @the-teacher 's fix

**Comment by jacek213** [comment]
+1

**Comment by keiththecomputerguy** [comment]
Thank you @the-teacher for the fix

**Comment by nhoffmann** [comment]
If it has not come to your attention yet, there is a maintained fork of this project by @seuros,
which is probably a better solution than to monkeypatch this abandoned project.

https://github.com/state-machines/state_machines

**Comment by keiththecomputerguy** [comment]
Thank You!

**Comment by thatandyrose** [comment]
thank you @seuros and @nhoffmann, just saved my bacon! :-)

**Comment by andrii** [comment]
+1

**Comment by WillTaylor22** [comment]
+1

**Comment by jerome2** [comment]
@keithgordon :
that i would like to do, but the fact is that i not see how to install and use this state_machines instead of the state_machine from rails-4.2.
The documentation is really big and full of data (to much maybe in one time ?) and then it's confused for me (i'm not an expert of rails too...).
Could you please be more explicit about "how to not use monkypatch (but really helpfull and simple) and use actives_machine" ?
Thanks again for help.

**Comment by ghost** [comment]
@the-teacher :
thanks for your patch. It was really simple to apply and offer a real solution in case of use your (really good) gems files.

**Comment by catmando** [comment]
word to the wise, while its great that somebody is supporting state_machine, it is not 100% the same behavior as the old state_machine gem... I suspect there were bugs in the old version that have been fixed.  At any rate, you might find during the upgrade the quickest fix is the monkey patch.

**Comment by akonan** [comment]
+1

**Comment by sennor** [comment]
+1

**Comment by rvsingh** [comment]
+1

**Comment by droupou** [comment]
Thanks @the-teacher, and @gingermusketeer!
