### ISSUE TITLE
protected method `around_validation' ERROR

### ISSUE THREAD

**Issue by kaiomagalhaes** [pluginaweek/state_machine#348]
While using the gem with rails 4.2 I have faced the following issue:

```
protected method `around_validation' called for #<StateMachine::Machine:0x00000004f953e0>
```

To fix this I have to add a monkey patch.
I added the following code inside config/initializers/state_machine_patch.rb

```
module StateMachine
  module Integrations
    module ActiveModel
      public :around_validation
    end
  end
end
```

There is any best way to fix it?

**Comment by twalpole** [comment]
This gem isn't supported anymore - check out the fork at https://github.com/state-machines/state_machines to see if it'll work for you

**Comment by kaiomagalhaes** [comment]
@twalpole Thanks for the information. The bad thing is that with this fork it shows up another error

```
ActiveRecord::RecordNotFound:
       Couldn't find Company with 'id'=
     # /var/lib/gems/2.2.0/gems/activerecord-4.2.5/lib/active_record/core.rb:155:in `find'
     # ./spec/models/company_spec.rb:17:in `block (3 levels) in <top (required)>'
```

**Comment by anklos** [comment]
thanks for the patch. just met the same issue.

this is a very useful gem, would be sad to see it left unmaintained.
