### ISSUE TITLE
Machine class yardoc page gives error: Invalid namespace object: StateMachine::Machine#owner_class

### ISSUE THREAD

**Issue by chrisdtaylor** [pluginaweek/state_machine#351]
http://www.rubydoc.info/github/pluginaweek/state_machine/StateMachine/Machine

Load that page and you get:

Invalid namespace object: StateMachine::Machine#owner_class
/home/app/rubydoc.info/vendor/bundle/ruby/2.3.0/bundler/gems/yard-08c3a8309296/lib/yard/code_objects/proxy.rb:58:in `initialize'
/home/app/rubydoc.info/vendor/bundle/ruby/2.3.0/bundler/gems/yard-08c3a8309296/lib/yard/registry_resolver.rb:81:in`new'
/home/app/rubydoc.info/vendor/bundle/ruby/2.3.0/bundler/gems/yard-08c3a8309296/lib/yard/registry_resolver.rb:81:in `lookup_by_path'
/home/app/rubydoc.info/vendor/bundle/ruby/2.3.0/bundler/gems/yard-08c3a8309296/lib/yard/registry.rb:302:in`resolve'
/home/app/rubydoc.info/vendor/bundle/ruby/2.3.0/bundler/gems/yard-08c3a8309296/lib/yard/templates/helpers/html_helper.rb:261:in `link_object'
/home/app/rubydoc.info/vendor/bundle/ruby/2.3.0/bundler/gems/yard-08c3a8309296/lib/yard/templates/helpers/base_helper.rb:91:in`linkify'
/home/app/rubydoc.info/vendor/bundle/ruby/2.3.0/bundler/gems/yard-08c3a8309296/lib/yard/templates/helpers/html_helper.rb:213:in `block in resolve_links'
/home/app/rubydoc.info/vendor/bundle/ruby/2.3.0/bundler/gems/yard-08c3a8309296/lib/yard/templates/helpers/html_helper.rb:191:in`gsub'
/home/app/rubydoc.info/vendor/bundle/ruby/2.3.0/bundler/gems/yard-08c3a8309296/lib/yard/templates/helpers/html_helper.rb:191:in `resolve_links'
/home/app/rubydoc.info/vendor/bundle/ruby/2.3.0/bundler/gems/yard-08c3a8309296/lib/yard/templates/helpers/html_helper.rb:46:in`htmlify'
/home/app/rubydoc.info/vendor/bundle/ruby/2.3.0/gems/yard-sd-0.0.4/lib/yard-sd/sequence_diagram_mixin.rb:5:in `htmlify'
/home/app/rubydoc.info/vendor/bundle/ruby/2.3.0/bundler/gems/yard-08c3a8309296/templates/default/docstring/html/text.erb:3:in`_erb_cache_10'
/home/app/rubydoc.info/vendor/bundle/ruby/2.3.0/bundler/gems/yard-08c3a8309296/lib/yard/templates/template.rb:279:in `erb'
/home/app/rubydoc.info/vendor/bundle/ruby/2.3.0/bundler/gems/yard-08c3a8309296/lib/yard/templates/template.rb:357:in`render_section'
/home/app/rubydoc.info/vendor/bundle/ruby/2.3.0/bundler/gems/yard-08c3a8309296/lib/yard/templates/template.rb:251:in `block (2 levels) in run'
/home/app/rubydoc.info/vendor/bundle/ruby/2.3.0/bundler/gems/yard-08c3a8309296/lib/yard/templates/template.rb:248:in`each'
/home/app/rubydoc.info/vendor/bundle/ruby/2.3.0/bundler/gems/yard-08c3a8309296/lib/yard/templates/template.rb:248:in `block in run'
/home/app/rubydoc.info/vendor/bundle/ruby/2.3.0/bundler/gems/yard-08c3a8309296/lib/yard/templates/template.rb:386:in`add_options'
/home/app/rubydoc.info/vendor/bundle/ruby/2.3.0/bundler/gems/yard-08c3a8309296/lib/yard/templates/template.rb:247:in `run'
/home/app/rubydoc.info/vendor/bundle/ruby/2.3.0/bundler/gems/yard-08c3a8309296/lib/yard/templates/template.rb:269:in`block in yieldall'
...

**Comment by AndrewRayCode** [comment]
ping @obrie
