### ISSUE TITLE
State-driven instance behavior for setters is bugged

### ISSUE THREAD

**Issue by obrie** [pluginaweek/state_machine#37]
**Kane** opened this issue

when defineing a method like

 @@@ ruby
 state_machine :state, :initial => :applicating do
   state :applicating do
      def fame_buy_in=(value)
        write_attribute(:fame_buy_in, value)
      end
    end
  end
 @@@ 

an ArgumentError is thrown while trying to create a new object with .new(:fame_buy_in=>12)

ArgumentError: nil is not a known state value
E:/DEV/ruby/lib/ruby/gems/1.8/gems/pluginaweek-state_machine-0.7.6/lib/state_machine/state_collection.rb:80:in `match!&rsquo;
    E:/DEV/ruby/lib/ruby/gems/1.8/gems/pluginaweek-state_machine-0.7.6/lib/state_machine/state.rb:170:in`fame_buy_in=&rsquo;
    E:/DEV/ruby/lib/ruby/gems/1.8/gems/pluginaweek-state_machine-0.7.6/lib/state_machine/extensions.rb:30:in `initialize

[original LH ticket](http://pluginaweek.lighthouseapp.com/projects/13288/tickets/27)

 This ticket has 0 attachment(s).

**Comment by obrie** [comment]
Thanks for the report! I&rsquo;ve got a solution which will be pushed shortly.

**Comment by obrie** [comment]
(from [ecfc0cfd59369866abd094bce5f69dc28469771f]) Allow static initial states to be set earlier in the initialization of an object [#27 state:resolved]
Fix initial states being set when loading records from the database in Sequel integration
http://github.com/pluginaweek/state_machine/commit/ecfc0cfd59369866abd094bce5f69dc28469771f
