### ISSUE TITLE
StateMachine::InvalidTransition raised with valid event for current state

### ISSUE THREAD

**Issue by obrie** [pluginaweek/state_machine#45]
**David North** opened this issue

I have a Page model record with state &rsquo;published&rsquo;, 

 @page.state_events => [:draft, :unpublish]

But when I call draft! or unpublish! StateMachine::InvalidTransition is raised. (@page.draft returns false)

"Cannot transition state via :draft from :published"

/event.rb:248:in `add_actions&rsquo;
/machine.rb:512:in`call&rsquo;
/machine.rb:512:in `draft!&rsquo;

Version 0.8, Rails 2.3.4

It looks like draft/published is returning false because of my model being invalid so I guess the problem is that this isn&rsquo;t an appropriate error, its really that it failed to save the change in state, not that the transition was invalid.

Thanks

[original LH ticket](http://pluginaweek.lighthouseapp.com/projects/13288/tickets/35)

 This ticket has 0 attachment(s).

**Comment by obrie** [comment]
**schof** commented

 @David: I was just about to report the same ticket but I see you beat me to it.  I think we should distinguish between state machine logic preventing you from transitioning vs. a general exception or validation error preventing you form transitioning.

**Comment by obrie** [comment]
Hey guys,

This is an interesting issue.  I think the way I would look at it is that invoking events directly will result in exceptions only relating to that event.  That is, if you try to invoke an event, then if it&rsquo;s not able to transition for _any_ reason, the exception that gets raised is for the event.  It doesn&rsquo;t actually care why it was unable to transition.

The other important thing to keep in mind is that sometimes validations are specifically meant to block a transition from occurring.  An example of this is in the README:

 @@@ ruby
class Vehicle < ActiveRecord::Base
  state_machine do
    ...
    state :first_gear, :second_gear do
      validates_presence_of :seatbelt_on
    end
  end
end
 @@@

If you want to distinguish between the inability to transition and a failed validation, I would recommend not using the bang method.

As an example:

 @@@ ruby
class User < ActiveRecord::Base
  validates_presence_of :name

  state_machine :initial => :pending do
    event :activate do
      transition :pending => :active
    end

```
event :deactivate do
  transition :active => :pending
end
```

  end
end

user = User.new     # => => #<User id: nil, name: nil, state: "pending">
user.activate       # => false
user.errors         # => #<OrderedHash {:name=>["can&rsquo;t be blank"]}>

user = User.new
user.name = &rsquo;John&rsquo;  # =>  #<User id: nil, name: "John Smith", state: "pending">
user.deactivate     # => false
user.errors         # => #<OrderedHash {:state_event=>["is invalid"]}>
 @@@

Notice, from this example, that you can now differentiate between cases when a transition failed because of a validation versus because of an actual invalid transition.

I agree that it could be easier in cases where you just want to catch exceptions and easily differentiate between failure reasons by exception type.  However, I don&rsquo;t think that inspecting the validation errors is terribly worse.
