### ISSUE TITLE
Confusing InvalidTransition error - this should work

### ISSUE THREAD

**Issue by obrie** [pluginaweek/state_machine#56]
**Jonas Grimfelt** opened this issue

My ActiveRecord model with migrations OK, and payment_state-value &rsquo;unconfirmed&rsquo; and handling_state-value &rsquo;unconfirmed&rsquo; in DB:

 @@@ ruby
class Order < ActiveRecord::Base

  state_machine :handling_state, :initial => :unconfirmed, :namespace => :handling do
    state :unconfirmed
    state :new
    state :open
    state :shipped
    state :canceled

```
event :confirm do
  transition :unconfirmed => :new
end
```

  end

  state_machine :payment_state, :initial => :unconfirmed, :namespace => :payment do
    state :unconfirmed
    state :pending
    state :charged
    state :refunded

```
event :confirm do
  transition :unconfirmed => :pending
end
```

  end
end
 @@@

Calls:

 @@@ ruby
 @order = Order.new
 @order.confirm_handling! # ...so far so good, but now:
 @order.confirm_payment! # BANG! =(
 @@@

Error:

 @@@
StateMachine::InvalidTransition: Cannot transition payment_state via :confirm from :unconfirmed
    from /opt/local/lib/ruby/gems/1.8/gems/state_machine-0.9.2/lib/state_machine/event.rb:248:in `add_actions&rsquo;
    from /opt/local/lib/ruby/gems/1.8/gems/state_machine-0.9.2/lib/state_machine/machine.rb:537:in`call&rsquo;
    from /opt/local/lib/ruby/gems/1.8/gems/state_machine-0.9.2/lib/state_machine/machine.rb:537:in `confirm_payment!&rsquo;
    from (irb):39
    from :0
 @@@

Calling order.confirm_payment! fails no matter what order I call them in. I&rsquo;m stuck. =/

[original LH ticket](http://pluginaweek.lighthouseapp.com/projects/13288/tickets/46)

 This ticket has 0 attachment(s).

**Comment by obrie** [comment]
**Jonas Grimfelt** commented

Note: I&rsquo;m on Rails 2.3.8, Ruby 1.8.7

**Comment by obrie** [comment]
Jonas,

I can&rsquo;t reproduce this issue with the scenario above.  I suspect what&rsquo;s happening is that the record is failing to save (perhaps some before/after callback or a validation is failing).

Try calling @order.confirm_payment (no bang) and inspect the record to see if there are any validation errors (or anything that might indicate why the save is failing).

Hope this helps.
