### ISSUE TITLE
undefined method `call' for nil:NilClass

### ISSUE THREAD

**Issue by obrie** [pluginaweek/state_machine#71]
**Brent** opened this issue

I&rsquo;m trying to use state_machine (0.9.4) with MongoMapper and having an issue when saving documents. I&rsquo;ve used SM a few times now with ActiveRecord and it has worked perfectly, but this is my first attempt with MM.

I tried clearing out my entire model as well as state machine to cut anything out, and the error only exists when I include state_machine in my model. I tried poking around in the source to see if I could narrow it down as well but didn&rsquo;t have any luck :)

Here is my model (with pretty much everything but attributes and sm cleared out.... still fails like this):

 @@@ ruby  
    class Submission
      include MongoMapper::Document

```
    key :name, String
    key :video_state, String

    define_attribute_methods, [:video_state]

    state_machine :video_state, :initial => :added do
    end

end
```

 @@@

I originally had a few states and events listed, but removed them to be safe. I also had to add define_attribute_methods to avoid another error with MM. (undefined method map! for nil). Whenever I try to save the model I get the following stack trace:

 @@@
   vendor/bundle/ruby/1.9.1/gems/activesupport-3.0.0/lib/active_support/whiny_nil.rb:48:in `method_missing&rsquo;
vendor/bundle/ruby/1.9.1/gems/activemodel-3.0.0/lib/active_model/validator.rb:183:in`validate_each&rsquo;
vendor/bundle/ruby/1.9.1/gems/activemodel-3.0.0/lib/active_model/validator.rb:154:in `block in validate&rsquo;
vendor/bundle/ruby/1.9.1/gems/activemodel-3.0.0/lib/active_model/validator.rb:151:in`each&rsquo;
vendor/bundle/ruby/1.9.1/gems/activemodel-3.0.0/lib/active_model/validator.rb:151:in `validate&rsquo;
vendor/bundle/ruby/1.9.1/gems/activesupport-3.0.0/lib/active_support/callbacks.rb:314:in`_callback_before_521&rsquo;
vendor/bundle/ruby/1.9.1/gems/activesupport-3.0.0/lib/active_support/callbacks.rb:414:in `_run_validate_callbacks&rsquo;
vendor/bundle/ruby/1.9.1/gems/activemodel-3.0.0/lib/active_model/validations.rb:212:in`run_validations!&rsquo;
vendor/bundle/ruby/1.9.1/bundler/gems/mongomapper-fd59b0ab068b/lib/mongo_mapper/plugins/embedded_callbacks.rb:42:in `block in run_validations!&rsquo;
vendor/bundle/ruby/1.9.1/gems/activesupport-3.0.0/lib/active_support/callbacks.rb:418:in`_run_validation_callbacks&rsquo;
vendor/bundle/ruby/1.9.1/gems/activesupport-3.0.0/lib/active_support/callbacks.rb:93:in `run_callbacks&rsquo;
vendor/bundle/ruby/1.9.1/bundler/gems/mongomapper-fd59b0ab068b/lib/mongo_mapper/plugins/embedded_callbacks.rb:30:in`run_callbacks&rsquo;
vendor/bundle/ruby/1.9.1/bundler/gems/mongomapper-fd59b0ab068b/lib/mongo_mapper/plugins/embedded_callbacks.rb:42:in `run_validations!&rsquo;
vendor/bundle/ruby/1.9.1/gems/activemodel-3.0.0/lib/active_model/validations.rb:179:in`valid?&rsquo;
vendor/bundle/ruby/1.9.1/bundler/gems/mongomapper-fd59b0ab068b/lib/mongo_mapper/plugins/callbacks.rb:23:in `valid?&rsquo;
vendor/bundle/ruby/1.9.1/gems/state_machine-0.9.4/lib/state_machine/integrations/active_model.rb:372:in`block (3 levels) in define_action_helpers&rsquo;
vendor/bundle/ruby/1.9.1/gems/state_machine-0.9.4/lib/state_machine/transition_collection.rb:149:in `block in run_actions&rsquo;
vendor/bundle/ruby/1.9.1/gems/state_machine-0.9.4/lib/state_machine/transition_collection.rb:169:in`catch_exceptions&rsquo;
vendor/bundle/ruby/1.9.1/gems/state_machine-0.9.4/lib/state_machine/transition_collection.rb:147:in `run_actions&rsquo;
vendor/bundle/ruby/1.9.1/gems/state_machine-0.9.4/lib/state_machine/transition_collection.rb:132:in`run_callbacks&rsquo;
vendor/bundle/ruby/1.9.1/gems/state_machine-0.9.4/lib/state_machine/transition_collection.rb:211:in `run_callbacks&rsquo;
vendor/bundle/ruby/1.9.1/gems/state_machine-0.9.4/lib/state_machine/transition_collection.rb:63:in`block (2 levels) in perform&rsquo;
vendor/bundle/ruby/1.9.1/gems/state_machine-0.9.4/lib/state_machine/transition_collection.rb:63:in `catch&rsquo;
vendor/bundle/ruby/1.9.1/gems/state_machine-0.9.4/lib/state_machine/transition_collection.rb:63:in`block in perform&rsquo;
vendor/bundle/ruby/1.9.1/gems/state_machine-0.9.4/lib/state_machine/transition_collection.rb:185:in `within_transaction&rsquo;
vendor/bundle/ruby/1.9.1/gems/state_machine-0.9.4/lib/state_machine/transition_collection.rb:62:in`perform&rsquo;
vendor/bundle/ruby/1.9.1/gems/state_machine-0.9.4/lib/state_machine/integrations/active_model.rb:372:in `block (2 levels) in define_action_helpers&rsquo;
vendor/bundle/ruby/1.9.1/bundler/gems/mongomapper-fd59b0ab068b/lib/mongo_mapper/plugins/querying.rb:138:in`save&rsquo;
vendor/bundle/ruby/1.9.1/bundler/gems/mongomapper-fd59b0ab068b/lib/mongo_mapper/plugins/dirty.rb:22:in `block in save&rsquo;
vendor/bundle/ruby/1.9.1/bundler/gems/mongomapper-fd59b0ab068b/lib/mongo_mapper/plugins/dirty.rb:44:in`clear_changes&rsquo;
vendor/bundle/ruby/1.9.1/bundler/gems/mongomapper-fd59b0ab068b/lib/mongo_mapper/plugins/dirty.rb:22:in `save&rsquo;
vendor/bundle/ruby/1.9.1/bundler/gems/mongomapper-fd59b0ab068b/lib/mongo_mapper/plugins/keys.rb:216:in`update_attributes&rsquo;
vendor/bundle/ruby/1.9.1/bundler/gems/mongomapper-fd59b0ab068b/lib/mongo_mapper/plugins/accessible.rb:25:in `update_attributes&rsquo;
vendor/bundle/ruby/1.9.1/bundler/gems/mongomapper-fd59b0ab068b/lib/mongo_mapper/plugins/protected.rb:34:in`update_attributes&rsquo;
 @@@

When removing state_machine completely, everything works as expected.

[original LH ticket](http://pluginaweek.lighthouseapp.com/projects/13288/tickets/61)

 This ticket has 0 attachment(s).

**Comment by obrie** [comment]
**Michael Schmidt** commented

It seems like this is an incompatibility with the rails3 branch of mongo_mapper. The integration tests for mongo run fine against https://github.com/jnunemaker/mongomapper/tree/v0.8.6 but fail for https://github.com/jnunemaker/mongomapper/tree/rails3.

There&rsquo;s basically only two problems which make the tests fail:

NoMethodError: undefined method `call&rsquo; for nil:NilClass
    /ruby-1.8.7-p302@state_machine/gems/activemodel-3.0.3/lib/active_model/validator.rb:183:in`validate_each
    See above...

NoMethodError: undefined method `state_changed?&rsquo; for #<MongoMapperTest::foo _id: nil, state: "parked">
    /ruby-1.8.7-p302@state_machine/gems/activemodel-3.0.3/lib/active_model/attribute_methods.rb:364:in`method_missing&rsquo;
    /Git/state_machine/test/../lib/state_machine/integrations/active_model.rb:255:in `send&rsquo;

Looks like it might be not that hard to fix but I&rsquo;m lost to what actually needs doing.

**Comment by obrie** [comment]
Michael -

Thanks for letting me know about the latest incompatibility.  I&rsquo;m working on some changes to the integrations so that it&rsquo;ll be easier to keep up-to-date with the latest changes in each integration.  I&rsquo;ll make sure this gets fixed after that work is done.

**Comment by obrie** [comment]
(from [7a935e8770e16eaff3f590b4e3b30e0868f633c7]) Update support for MongoMapper integration based on rails3 branch (MongoMapper version must be bumped to 0.9.0 or greater)
https://github.com/pluginaweek/state_machine/commit/7a935e8770e16eaff3f590b4e3b30e0868f633c7
