### ISSUE TITLE
after_transition callbacks with :include_failures don't work

### ISSUE THREAD

**Issue by obrie** [pluginaweek/state_machine#72]
**Chad** opened this issue

I&rsquo;m trying to get an `after_transition` callback to work even when the transition fails by specifying the `include_failures` option per the documentation, but it&rsquo;s not being called.  You can see from a simple irb session:

<code>
ruby-1.8.7-p174 > class Simple
ruby-1.8.7-p174 ?>  state_machine :state, :initial => :off do
ruby-1.8.7-p174 >       after_transition :include_failures => true do |object, transition|
ruby-1.8.7-p174 >         puts "FAILED"
ruby-1.8.7-p174 ?>      end
ruby-1.8.7-p174 ?>  
ruby-1.8.7-p174 >       event :activate do
ruby-1.8.7-p174 >         transition all => :on, :if => lambda{false}
ruby-1.8.7-p174 ?>      end
ruby-1.8.7-p174 ?>  
ruby-1.8.7-p174 >       state :off
ruby-1.8.7-p174 ?>    state :on
ruby-1.8.7-p174 ?>    end
ruby-1.8.7-p174 ?>  end
 => #<StateMachine::Machine:0x1010a1c28 @instance_helper_module=#<Module:0x1010a07b0>, @messages={}, @owner_class=Simple, @callbacks={:before=>[], :after=>[#<StateMachine::Callback:0x10109e898 @methods=[#<Proc:0x00000001010a2628@(irb):7>], @type=:after, @guard=#<StateMachine::Guard:0x10109e730 @event_requirement=#<StateMachine::AllMatcher:0x10109e5f0 @values=[]>, @state_requirements=[{:to=>#<StateMachine::AllMatcher:0x10109e5f0 @values=[]>, :from=>#<StateMachine::AllMatcher:0x10109e5f0 @values=[]>}], @known_states=[], @unless_condition=nil, @success_requirement=#<StateMachine::AllMatcher:0x10109e5f0 @values=[]>, @if_condition=nil>, @terminator=nil>]}, @events=#<StateMachine::EventCollection:0x1010a1818 @indices={:qualified_name=>{:activate=>#<StateMachine::Event name=:activate transitions=[all => :on]>}, :name=>{:activate=>#<StateMachine::Event name=:activate transitions=[all => :on]>}}, @nodes=[#<StateMachine::Event name=:activate transitions=[all => :on]>], @machine=#<StateMachine::Machine:0x1010a1c28 ...>, @default_index=:name>, @namespace=nil, @use_transactions=true, @attribute=:state, @class_helper_module=#Module:0x1010a0850, @initial_state=:off, @states=#<StateMachine::StateCollection:0x1010a1840 @indices={:value=>{"off"=>#<StateMachine::State name=:off value="off" initial=true context=[]>, "on"=>#<StateMachine::State name=:on value="on" initial=false context=[]>}, :name=>{:off=>#<StateMachine::State name=:off value="off" initial=true context=[]>, :on=>#<StateMachine::State name=:on value="on" initial=false context=[]>}}, @nodes=[#<StateMachine::State name=:off value="off" initial=true context=[]>, #<StateMachine::State name=:on value="on" initial=false context=[]>], @machine=#<StateMachine::Machine:0x1010a1c28 ...>, @default_index=:name>, @action=nil, @name=:state> 
ruby-1.8.7-p174 > s = Simple.new
 => #<Simple:0x1010977a0 @state="off"> 
ruby-1.8.7-p174 > s.activate!
StateMachine::InvalidTransition: Cannot transition state via :activate from :off
    from /Users/cboyd/.rvm/gems/ruby-1.8.7-p174@petrus/gems/state_machine-0.9.4/lib/state_machine/event.rb:263:in `add_actions&rsquo;
    from /Users/cboyd/.rvm/gems/ruby-1.8.7-p174@petrus/gems/state_machine-0.9.4/lib/state_machine/machine.rb:537:in`call&rsquo;
    from /Users/cboyd/.rvm/gems/ruby-1.8.7-p174@petrus/gems/state_machine-0.9.4/lib/state_machine/machine.rb:537:in `activate!&rsquo;
    from (irb):20
</code>

Am I doing something wrong?

[original LH ticket](http://pluginaweek.lighthouseapp.com/projects/13288/tickets/62)

 This ticket has 0 attachment(s).

**Comment by obrie** [comment]
**Chad** commented

After looking into this some more, I think it has something to do with [this](http://github.com/pluginaweek/state_machine/blob/master/lib/state_machine/transition_collection.rb#L53) line.  If `valid?` returns false, the callbacks never get called.  Shouldn&rsquo;t they, though, if `include_failures` is specified?

**Comment by obrie** [comment]
Hi Chad,

Thanks for the test case.  I&rsquo;ve thought a little bit about this one and this has me thinking that :include_failures was basically a hack when I changed how transitions got run a long time ago.  I&rsquo;m working on a new API to specifically define callbacks that get run under all failure scenarios.  I&rsquo;ll update this bug when those changes make their way to github.

**Comment by obrie** [comment]
(from [eb77529404b211f9d6a5564f9175771dea0ee1ed]) Replace :include_failures after_transition option with new after_failure callback [#62 state:resolved]
https://github.com/pluginaweek/state_machine/commit/eb77529404b211f9d6a5564f9175771dea0ee1ed
