### ISSUE TITLE
undefined method `arity' for nil:NilClass

### ISSUE THREAD

**Issue by obrie** [pluginaweek/state_machine#75]
**RailsCanuck** opened this issue

I have several classes that I am using state_machine for my rails app and I am getting the following error while using state_machine in only one of these classes, the rest work fine which is confusing. The class name is Shipment and it has several classes that inherit from Shipment including DropShipment and OutgoingShipment.

 @@@
NoMethodError: undefined method `arity&rsquo; for nil:NilClass
    from /activesupport-3.0.3/lib/active_support/whiny_nil.rb:48:in`method_missing&rsquo;
    from /state_machine-0.9.4/lib/state_machine/eval_helpers.rb:56:in `evaluate_method&rsquo;
    from /state_machine-0.9.4/lib/state_machine/callback.rb:196:in`block in run_methods&rsquo;
    from /state_machine-0.9.4/lib/state_machine/callback.rb:195:in `each&rsquo;
    from /state_machine-0.9.4/lib/state_machine/callback.rb:195:in`run_methods&rsquo;
    from /state_machine-0.9.4/lib/state_machine/callback.rb:158:in `call&rsquo;
    from /state_machine-0.9.4/lib/state_machine/transition.rb:379:in`block (2 levels) in after&rsquo;
    from /state_machine-0.9.4/lib/state_machine/transition.rb:379:in `each&rsquo;
    from /state_machine-0.9.4/lib/state_machine/transition.rb:379:in`block in after&rsquo;
    from /state_machine-0.9.4/lib/state_machine/transition.rb:377:in `catch&rsquo;
    from /state_machine-0.9.4/lib/state_machine/transition.rb:377:in`after&rsquo;
    from /state_machine-0.9.4/lib/state_machine/transition.rb:193:in `run_callbacks&rsquo;
    from /state_machine-0.9.4/lib/state_machine/transition_collection.rb:126:in`run_callbacks&rsquo;
    from /state_machine-0.9.4/lib/state_machine/transition_collection.rb:211:in `run_callbacks&rsquo;
    from /state_machine-0.9.4/lib/state_machine/transition_collection.rb:63:in`block (2 levels) in perform&rsquo;
    from /state_machine-0.9.4/lib/state_machine/transition_collection.rb:63:in `catch&rsquo;
... 16 levels...
    from /state_machine-0.9.4/lib/state_machine/transition_collection.rb:153:in`each&rsquo;
    from /state_machine-0.9.4/lib/state_machine/transition_collection.rb:153:in `block in run_actions&rsquo;
    from /state_machine-0.9.4/lib/state_machine/transition_collection.rb:169:in`catch_exceptions&rsquo;
    from /state_machine-0.9.4/lib/state_machine/transition_collection.rb:147:in `run_actions&rsquo;
    from /state_machine-0.9.4/lib/state_machine/transition_collection.rb:60:in`perform&rsquo;
    from /state_machine-0.9.4/lib/state_machine/transition.rb:162:in `perform&rsquo;
    from /state_machine-0.9.4/lib/state_machine/event.rb:207:in`fire&rsquo;
    from /state_machine-0.9.4/lib/state_machine/event.rb:258:in `block in add_actions&rsquo;
    from /state_machine-0.9.4/lib/state_machine/machine.rb:537:in`call&rsquo;
    from /state_machine-0.9.4/lib/state_machine/machine.rb:537:in `block (2 levels) in define_instance_method&rsquo;
 @@@

The error occur when using the callback where I have

 @@@
state_machine :status, :initial => :pending do
    event :ship do
      transition :confirm_shipping => :shipping
    end
    after_transition :confirm_shipping => :shipping, :do => :check_order_completion
end

def check_order_completion
   orders.map(&:complete)
end
 @@@

It is quite clear that somehow the method being passed in &rsquo;:check_order_completion&rsquo; has a null object. As a band-aid I changed the method call from a symbol to a string as follows and all works fine.

 @@@
after_transition :confirm_shipping => :shipping, :do => &rsquo;check_order_completion&rsquo;
 @@@

This issue was bothering me for a while but once I looked at the state_machine source code and noticed that the callback accepts symbols, blocks, or strings then that helped to solve my problem but I thought it would be worth noting the bug on the null object being passed into evaluate_method in eval_helpers.

[original LH ticket](http://pluginaweek.lighthouseapp.com/projects/13288/tickets/65)

 This ticket has 0 attachment(s).

**Comment by obrie** [comment]
Hey RailsCanuck -

I&rsquo;m unable to reproduce this scenario.  If you could provide a test case with full code that demonstrates this behavior, that would be great.  The error only occurs when state_machine is unable to find the method referenced in the callback.  This would indicate to me that something strange was going on with the objects you were interacting with.

Feel free to reopen if you can find a case that I can reproduce.
