### ISSUE TITLE
"no acceptor" error when running on thin webserver

### ISSUE THREAD

**Issue by obrie** [pluginaweek/state_machine#84]
**Matthew Windwer** opened this issue

We have an interesting situation where initialization of a state_machine model in Rails fails only on the thin webserver. The error we are getting is "#<RuntimeError: no acceptor>". I am not sure exactly why, but the problem seems to occur in #define_state_initializer and therefore only occurs when @initialize_state is set to true in machine.rb. There does not seem to be a way to set this to false without manually editing that file because of the following line of code:

<code>
options = {:use_transactions => true, :initialize => true}.merge(options)
</code>

I&rsquo;m not too familiar with the inner workings of state_machine yet and am not sure why we are getting this error only on thin.  Any ideas?  I am up for helping out with any debugging and testing that is necessary to resolve this issue.

If it is of any help, this is the backtrace:

<code>
RuntimeError: no acceptor
/eventmachine-0.12.10/lib/eventmachine.rb:572:in `start_tcp_server&rsquo;
/home/matthew/.rvm/gems/ruby-1.8.7-p302/gems/eventmachine-0.12.10/lib/eventmachine.rb:572:in`start_server&rsquo;
/home/matthew/.rvm/gems/ruby-1.8.7-p302/gems/thin-1.2.11/lib/thin/backends/tcp_server.rb:16:in `connect&rsquo;
/home/matthew/.rvm/gems/ruby-1.8.7-p302/gems/thin-1.2.11/lib/thin/backends/base.rb:53:in`start&rsquo;
/home/matthew/.rvm/gems/ruby-1.8.7-p302/gems/activerecord-3.0.5/lib/active_record/base.rb:1408:in `initialize&rsquo;
/home/matthew/.rvm/gems/ruby-1.8.7-p302/gems/state_machine-0.10.0/lib/state_machine/machine.rb:544:in`initialize&rsquo;
/home/matthew/.rvm/gems/ruby-1.8.7-p302/gems/state_machine-0.10.0/lib/state_machine/integrations/active_record.rb:389:in `call&rsquo;
/home/matthew/.rvm/gems/ruby-1.8.7-p302/gems/state_machine-0.10.0/lib/state_machine/integrations/active_record.rb:389:in`define_state_initializer&rsquo;
/home/matthew/.rvm/gems/ruby-1.8.7-p302/gems/state_machine-0.10.0/lib/state_machine/machine.rb:561:in `call&rsquo;
/home/matthew/.rvm/gems/ruby-1.8.7-p302/gems/state_machine-0.10.0/lib/state_machine/machine.rb:561:in`call_helper&rsquo;
/home/matthew/.rvm/gems/ruby-1.8.7-p302/gems/state_machine-0.10.0/lib/state_machine/machine.rb:545:in `initialize&rsquo;
/home/matthew/work/project/app/controllers/events_controller.rb:8:in`new&rsquo;
</code>

Thanks
Matthew

[original LH ticket](http://pluginaweek.lighthouseapp.com/projects/13288/tickets/74)

 This ticket has 1 attachment(s).

**Comment by obrie** [comment]
**Matthew Windwer** commented

I hope this backtrace will be easier to read:

#<RuntimeError: no acceptor>
/gems/eventmachine-0.12.10/lib/eventmachine.rb:572:in `start_tcp_server&rsquo;
/gems/eventmachine-0.12.10/lib/eventmachine.rb:572:in`start_server&rsquo;
/gems/thin-1.2.11/lib/thin/backends/tcp_server.rb:16:in `connect&rsquo;
/gems/thin-1.2.11/lib/thin/backends/base.rb:53:in`start&rsquo;
/gems/activerecord-3.0.5/lib/active_record/base.rb:1408:in `initialize&rsquo;
/gems/state_machine-0.10.0/lib/state_machine/machine.rb:544:in`initialize&rsquo;
/gems/state_machine-0.10.0/lib/state_machine/integrations/active_record.rb:389:in `call&rsquo;
/gems/state_machine-0.10.0/lib/state_machine/integrations/active_record.rb:389:in`define_state_initializer&rsquo;
/gems/state_machine-0.10.0/lib/state_machine/machine.rb:561:in `call&rsquo;
/gems/state_machine-0.10.0/lib/state_machine/machine.rb:561:in`call_helper&rsquo;
/gems/state_machine-0.10.0/lib/state_machine/machine.rb:545:in `initialize&rsquo;
/home/matthew/work/project/app/controllers/events_controller.rb:8:in`new&rsquo;

**Comment by obrie** [comment]
**Matthew Windwer** commented

LOL I&rsquo;ll just attach that a file

**Comment by obrie** [comment]
See http://mrjaba.posterous.com/starttcpserver-no-acceptor-runtimeerror

Although state_machine is in the stack trace, it isn&rsquo;t actually causing the error.

**Comment by obrie** [comment]
**Joe Martinez** commented

I think it is state_machine causing the error. I had the same problem after upgrading state_machine from 0.9.4 to 0.10.1. Rolled back to 0.9.4 and the problem is gone.

Thanks for this state_machine implementation by the way, by far my favorite.

**Comment by obrie** [comment]
Hm that&rsquo;s interesting.  I can definitely reproduce it locally.  Let me look into this a little bit more and I&rsquo;ll let you know what I find.

**Comment by obrie** [comment]
FYI I believe I have a fix, but it&rsquo;ll take a few days to make its way up to github and some of the code involved is a little in flux right now.  I&rsquo;ll update the ticket when the fix is in.  I suspect a release with it will be made available in about a week and a half.

Thanks to both of you for reporting this and following up.

**Comment by obrie** [comment]
(from [ff050bdf451a0597756dcf7cf3dae08d37248598]) Simplify helpers by allowing the use of string evaluation
- Fixes helpers failing when used with certain libraries (such as Thin) [#74 state:resolved]
  https://github.com/pluginaweek/state_machine/commit/ff050bdf451a0597756dcf7cf3dae08d37248598

**Comment by obrie** [comment]
Turns out I had a fix more quickly than I thought.  There still won&rsquo;t be a release until next week with this fix, but at least you can use state_machine with Thin based on the latest in master.

**Comment by obrie** [comment]
**Joe Martinez** commented

That&rsquo;s awesome. Thanks Aaron!

**Comment by obrie** [comment]
**Matthew Windwer** commented

Ok thanks!
