### ISSUE TITLE
State machine check transition conditions when it is not necessary

### ISSUE THREAD

**Issue by obrie** [pluginaweek/state_machine#87]
**petRUShka** opened this issue

I have Ratification model with state machine included:

```
class Ratification < ActiveRecord::Base
  state_machine :status, :initial => :boss do
    state :boss
    state :owner
    state :done

    event :approve do
      transition :boss => :done, :if => :is_declarant_or_user_owner?
      transition :boss => :owner
    end
  end 

  def is_declarant_or_user_owner?
    # some code that broken if ratification isn&rsquo;t filled right
  end
end
```

When I try to create it with wrong params hash I get an error in `is_declarant_or_user_owner?` with such backtrace below. It is very strange because of call of `is_declarant_or_user_owner?`. I have no transition and so I expected to not call `is_declarant_or_user_owner?`. 

Backtrace:

```
/home/user/.rvm/gems/ruby-1.8.7-p302/gems/activesupport-2.3.10/lib/active_support/whiny_nil.rb:52:in `method_missing&rsquo;
/home/user/webdev/sd-portal/app/models/ratification.rb:177:in `is_declarant_or_user_owner?&rsquo;
/home/user/.rvm/gems/ruby-1.8.7-p302/gems/state_machine-0.10.4/lib/state_machine/eval_helpers.rb:56:in `send&rsquo;
/home/user/.rvm/gems/ruby-1.8.7-p302/gems/state_machine-0.10.4/lib/state_machine/eval_helpers.rb:56:in `evaluate_method&rsquo;
/home/user/.rvm/gems/ruby-1.8.7-p302/gems/state_machine-0.10.4/lib/state_machine/branch.rb:220:in `matches_conditions?&rsquo;
/home/user/.rvm/gems/ruby-1.8.7-p302/gems/activerecord-2.3.10/lib/active_record/attribute_methods.rb:211:in `all?&rsquo;
/home/user/.rvm/gems/ruby-1.8.7-p302/gems/state_machine-0.10.4/lib/state_machine/branch.rb:220:in `each&rsquo;
/home/user/.rvm/gems/ruby-1.8.7-p302/gems/state_machine-0.10.4/lib/state_machine/branch.rb:220:in `all?&rsquo;
/home/user/.rvm/gems/ruby-1.8.7-p302/gems/state_machine-0.10.4/lib/state_machine/branch.rb:220:in `matches_conditions?&rsquo;
/home/user/.rvm/gems/ruby-1.8.7-p302/gems/state_machine-0.10.4/lib/state_machine/branch.rb:121:in `match&rsquo;
/home/user/.rvm/gems/ruby-1.8.7-p302/gems/state_machine-0.10.4/lib/state_machine/event.rb:212:in `transition_for&rsquo;
/home/user/.rvm/gems/ruby-1.8.7-p302/gems/state_machine-0.10.4/lib/state_machine/event.rb:211:in `each&rsquo;
/home/user/.rvm/gems/ruby-1.8.7-p302/gems/state_machine-0.10.4/lib/state_machine/event.rb:211:in `transition_for&rsquo;
/home/user/.rvm/gems/ruby-1.8.7-p302/gems/state_machine-0.10.4/lib/state_machine/event_collection.rb:119:in `attribute_transition_for&rsquo;
/home/user/.rvm/gems/ruby-1.8.7-p302/gems/state_machine-0.10.4/lib/state_machine/machine_collection.rb:81:in `transitions&rsquo;
/home/user/.rvm/gems/ruby-1.8.7-p302/gems/activerecord-2.3.10/lib/active_record/attribute_methods.rb:211:in `map&rsquo;
/home/user/.rvm/gems/ruby-1.8.7-p302/gems/state_machine-0.10.4/lib/state_machine/machine_collection.rb:80:in `each&rsquo;
/home/user/.rvm/gems/ruby-1.8.7-p302/gems/state_machine-0.10.4/lib/state_machine/machine_collection.rb:80:in `map&rsquo;
/home/user/.rvm/gems/ruby-1.8.7-p302/gems/state_machine-0.10.4/lib/state_machine/machine_collection.rb:80:in `transitions&rsquo;
/home/user/.rvm/gems/ruby-1.8.7-p302/gems/state_machine-0.10.4/lib/state_machine/integrations/active_model/versions.rb:12:in `valid?&rsquo;
/home/user/.rvm/gems/ruby-1.8.7-p302/gems/activerecord-2.3.10/lib/active_record/validations.rb:1089:in `save_without_dirty&rsquo;
/home/user/.rvm/gems/ruby-1.8.7-p302/gems/activerecord-2.3.10/lib/active_record/dirty.rb:79:in `save_without_transactions&rsquo;
/home/user/.rvm/gems/ruby-1.8.7-p302/gems/activerecord-2.3.10/lib/active_record/transactions.rb:229:in `send&rsquo;
/home/user/.rvm/gems/ruby-1.8.7-p302/gems/activerecord-2.3.10/lib/active_record/transactions.rb:229:in `with_transaction_returning_status&rsquo;
/home/user/.rvm/gems/ruby-1.8.7-p302/gems/activerecord-2.3.10/lib/active_record/connection_adapters/abstract/database_statements.rb:136:in `transaction&rsquo;
/home/user/.rvm/gems/ruby-1.8.7-p302/gems/activerecord-2.3.10/lib/active_record/transactions.rb:182:in `transaction&rsquo;
/home/user/.rvm/gems/ruby-1.8.7-p302/gems/activerecord-2.3.10/lib/active_record/transactions.rb:228:in `with_transaction_returning_status&rsquo;
/home/user/.rvm/gems/ruby-1.8.7-p302/gems/activerecord-2.3.10/lib/active_record/transactions.rb:196:in `save&rsquo;
/home/user/.rvm/gems/ruby-1.8.7-p302/gems/activerecord-2.3.10/lib/active_record/transactions.rb:208:in `rollback_active_record_state!&rsquo;
/home/user/.rvm/gems/ruby-1.8.7-p302/gems/activerecord-2.3.10/lib/active_record/transactions.rb:196:in `save&rsquo;
/home/user/webdev/sd-portal/app/controllers/ratifications_controller.rb:86:in `create&rsquo;
```

Rails 2.3.10
State_machine 0.10.4

[original LH ticket](http://pluginaweek.lighthouseapp.com/projects/13288/tickets/77)

 This ticket has 0 attachment(s).

**Comment by obrie** [comment]
Hi,

Thanks for the report.  From the stack trace is looks like the status_event attribute on the object is getting set.  Can you provide more details around what attributes are getting passed in and what the value of status_event is in your instance when is_declarant_or_user_owner? gets called?

Without that information and a complete example that I can reproduce locally, it&rsquo;ll be difficult to debug what&rsquo;s going on.

**Comment by obrie** [comment]
**petRUShka** commented

I&rsquo;m very sorry, I frogot about `.status_event` = &rsquo;approve&rsquo; in controller :(

**Comment by obrie** [comment]
Glad you were able to figure it out.
